{  
   "version":"1.0",
   "encoding":"UTF-8",
   "entry":{ 
      "media$group":{  
         "media$content":[  
            {  
               "url":"https://learnmoreskill.github.io/json/10/11.jpg",
               "height":2169,
               "width":3840,
               "type":"image/jpeg",
               "medium":"image"
            }
         ]
      }
   }
}
